a_lr: 0.0001
algo: mappo
batch_size: 64
buffer_size: 100000
c_lr: 0.0001
clip_epsilon: 0.1
episode_length: 200
epsilon: 0.5
epsilon_speed: 0.99998
game_name: snakes_3v3
gamma: 0.95
lmbda: 0.98
load_model: false
load_model_run: 2
load_model_run_episode: 4000
log_dir: '20230518_170635'
max_episodes: 200
model_episode: 0
output_activation: softmax
save_interval: 100
seed: 1
tau: 0.001
update_interval: 10
